version: '3.8'
services:
  app:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - ${PWD}:/usr/src/app
      - /usr/src/app/dist
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
